[package]
name = "ledwall_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spout_rust = { path = "../spout_rust" }
cxx = "1.0.66"